Lesson2
SergeyLomakin/geekshop-server pull request #2
Opened 2021-04-25 11:24 UTC by SergeyLomakin

2021-04-27 06:55 UTC, Vokler requested changes

2021-04-27 06:55 UTC, vprinz commented on mainapp/templates/mainapp/products.html
> +            <hr>
А почему вы все блоки с продуктами удалили? Один оставьте, и там, где идет информация о нужном поле, вставьте.

2021-04-27 07:33 UTC, SergeyLomakin commented on mainapp/templates/mainapp/products.html
> +            <hr>
Исправил, создал новый коммит и запушил его. 
https://github.com/SergeyLomakin/geekshop-server/pull/2/commits/66a14d9a37e47f2996924c05a7cab57d0fb0a4a0 
(Вопрос: когда требуеться исправление, как в этой ситуации - как поступать? коммитить и пушить, как сделал я или как то по другому?)

2021-04-28 09:53 UTC, Vokler approved these changes

2021-04-28 09:53 UTC, merged